name 'influxdb'
maintainer 'Byron Schaller'
maintainer_email 'byron.schaller@gmail.com'
license 'all_rights'
description 'Installs/Configures influxdb'
long_description 'Installs/Configures influxdb'
version '0.1.0'
supports 'ubuntu'
issues_url 'https://github.com/byronschaller/influxdb/issues'
source_url 'https://github.com/byronschaller/influxdb'
